[tool.poetry]
name = "anyrepo"
version = "0.1.0"
description = "Multi Repository Management Tool"
authors = []

[tool.poetry.scripts]
anyrepo = 'anyrepo.cli:main'
ar = 'anyrepo.cli:main'

[tool.poetry.dependencies]
python = '>=3.7,<4'
click = '>=8.0.0'
pydantic = '>=1.10.0'
pyyaml = '>=6.0.0'

[tool.poetry.dev-dependencies]
black = '>=21.9b0'
pytest = '>=6.2'
pylint = '>=2.13.5'
isort = '>=5.9'
coverage = '>=6.4.4'
sphinx = '>=5.1.1'


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | \.tox
  | build
  | dist
  | setup\.py
)/
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
extension-pkg-whitelist = "pydantic"
disable = [
    # Add global exceptions here
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py
isolated_build = True

[tox:.package]
basepython = python3

[testenv]
allowlist_externals = *
commands = 
    poetry install
    black .
    isort .
    coverage run --branch -m pytest --doctest-glob=docs/*.rst --doctest-modules --ignore-glob=tests/testdata* --ignore=docs/conf.py --log-level=DEBUG -vv --junitxml=report.xml
    coverage report
    coverage html
    coverage xml
    pylint anyrepo
    make html -C docs
"""
